### ISSUE TITLE
running into problems during make

### ISSUE THREAD

**Issue by simha-hv** [Canjie-Luo/Text-Image-Augmentation#12]
Cloned the repo and tried building it.
Used the following command 
cmake .. -D CUDA_USE_STATIC_CUDA_RUNTIME=OFF -DPYTHON_INCLUDE_DIR=$(python -c "from distutils.sysconfig import get_python_inc; print(get_python_inc())") -DPYTHON_LIBRARY=$(python -c "import distutils.sysconfig as sysconfig; print(sysconfig.get_config_var('LIBDIR'))")

During make, getting this error log
In file included from /usr/include/python2.7/numpy/ndarraytypes.h:1809:0,
                 from /usr/include/python2.7/numpy/ndarrayobject.h:18,
                 from /y/x/Text-Image-Augmentation/include/conversion.h:8,
                 from /y/x/Text-Image-Augmentation/src/conversion.cpp:1:
/usr/include/python2.7/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^~~~~~~
 /y/x/Text-Image-Augmentation/src/conversion.cpp:119:16: error: cannot declare variable 'g_numpyAllocator' to be of abstract type 'NumpyAllocator'
 NumpyAllocator g_numpyAllocator;
                ^~~~~~~~~~~~~~~~
 /y/x/Text-Image-Augmentation/src/conversion.cpp:64:7: note:   because the following virtual functions are pure within 'NumpyAllocator':
 class NumpyAllocator : public MatAllocator
       ^~~~~~~~~~~~~~
In file included from /usr/include/opencv2/core.hpp:59:0,
                 from /usr/include/opencv2/imgproc.hpp:46,
                 from /usr/include/opencv2/imgproc/imgproc.hpp:48,
                 from  /y/x/Text-Image-Augmentation/include/conversion.h:5,
                 from  /y/x/Text-Image-Augmentation/src/conversion.cpp:1:
/usr/include/opencv2/core/mat.hpp:417:23: note: 	virtual cv::UMatData* cv::MatAllocator::allocate(int, const int*, int, void*, size_t*, int, cv::UMatUsageFlags) const
     virtual UMatData* allocate(int dims, const int* sizes, int type,
                       ^~~~~~~~
/usr/include/opencv2/core/mat.hpp:419:18: note: 	virtual bool cv::MatAllocator::allocate(cv::UMatData*, int, cv::UMatUsageFlags) const
     virtual bool allocate(UMatData* data, int accessflags, UMatUsageFlags usageFlags) const = 0;
                  ^~~~~~~~
/usr/include/opencv2/core/mat.hpp:420:18: note: 	virtual void cv::MatAllocator::deallocate(cv::UMatData*) const
     virtual void deallocate(UMatData* data) const = 0;
                  ^~~~~~~~~~
 /y/x/Text-Image-Augmentation/src/conversion.cpp: In member function 'cv::Mat NDArrayConverter::toMat(const PyObject*)':
 /y/x/Text-Image-Augmentation/src/conversion.cpp:202:11: error: 'class cv::Mat' has no member named 'refcount'
         m.refcount = refcountFromPyObject(o);
           ^~~~~~~~
 /y/x/Text-Image-Augmentation/src/conversion.cpp: In member function 'PyObject* NDArrayConverter::toNDArray(const cv::Mat&)':
 /y/x/Text-Image-Augmentation/src/conversion.cpp:223:12: error: 'class cv::Mat' has no member named 'refcount'
     if(!p->refcount || p->allocator != &g_numpyAllocator)
            ^~~~~~~~
 /y/x/Text-Image-Augmentation/src/conversion.cpp:230:36: error: 'class cv::Mat' has no member named 'refcount'
     return pyObjectFromRefcount(p->refcount);
                                    ^~~~~~~~
CMakeFiles/Augment.dir/build.make:75: recipe for target 'CMakeFiles/Augment.dir/src/conversion.cpp.o' failed
make[2]: *** [CMakeFiles/Augment.dir/src/conversion.cpp.o] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/Augment.dir/all' failed
make[1]: *** [CMakeFiles/Augment.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

python version - 2.7.17
opencv - 3.3.0
numpy - 1.13.3

**Comment by Canjie-Luo** [comment]
Please downgrade the OpenCV version~

**Comment by simha-hv** [comment]
Thank you. Worked with OpenCV 2.4.8

The issue can be closed now
